import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";

import { Button } from "@/components/ui/button";
import { CTASection, FeatureCard, PageHero, SectionHeading } from "@/components/marketing/primitives";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "About Ornigami | Calm tools for local businesses", description: "Learn why Ornigami builds practical, approval-first tools for local businesses and the teams behind them.", path: "/about" });

export default function AboutPage() {
  return <main><PageHero eyebrow="About" title="Built for the businesses that make a neighborhood." intro="Ornigami started from a simple frustration: great local businesses lose reviews and reputation not from bad work, but from not having time to keep up." /><section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 md:grid-cols-2 md:px-6 lg:px-8"><div><SectionHeading eyebrow="Our mission" title="A calmer way to keep the important moments moving." intro="We think small teams deserve tools that feel calm and do the quiet, repetitive reputation work — without taking over, and without pretending to be you." /><div className="mt-8 flex flex-wrap gap-3"><Button variant="accent" asChild><Link href="/signup">Start free trial <ArrowRight className="h-4 w-4" /></Link></Button><Button variant="secondary" asChild><Link href="/demo">See a live demo</Link></Button></div></div><div className="rounded-2xl border-[1.5px] border-border bg-tint-mint p-8 shadow-ink-sm"><p className="text-sm font-bold text-primary">How we work</p><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Approve-first, honest by default. Ornigami drafts and suggests; you decide. We never post fake reviews or pretend a draft is a real customer.</p><ul className="mt-7 space-y-4">{["Start with clear, useful workflows.", "Keep automation visible and approval-first.", "Design for busy people, not perfect conditions."].map((item) => <li key={item} className="flex gap-3 text-sm text-primary"><Check className="mt-0.5 h-4 w-4 shrink-0 text-accent-green" />{item}</li>)}</ul></div></section><section className="border-y border-border bg-surface py-20"><div className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8"><SectionHeading eyebrow="Our principles" title="Useful, human, and part of one system." align="center" tint="butter" /><div className="mt-12 grid gap-5 md:grid-cols-3"><FeatureCard icon="sparkles" title="Practical first" body="Every feature should make a real part of local work clearer or lighter." /><FeatureCard icon="heart-handshake" accent="green" title="Human in the loop" body="Automation supports judgment. It does not hide it or replace it." bullets={[]} /><FeatureCard icon="layers" accent="marigold" title="One calm system" body="Reviews, follow-ups, and visibility should feel like parts of one product." /></div></div></section><CTASection title="Give the quiet work a calmer home." body="Start free today, or explore Ornigami with sample data first." /></main>;
}
