import Link from "next/link";
import { ArrowRight, Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import { CTASection, FAQItem, FeatureCard, ProductFrame, SectionHeading } from "@/components/marketing/primitives";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Google review replies in your voice | Ornigami", description: "Draft thoughtful Google review replies in your tone, edit every response, and approve what gets posted.", path: "/review-replies" });

const faqs = [["Can I edit every draft?", "Yes. Every response is a draft until you approve it, so you can edit the wording before anything is posted."], ["What happens with negative reviews?", "You keep approval-first controls for every rating and can use the draft as a starting point for a thoughtful response."], ["Can I manage more than one location?", "For now, one location per subscription. Managing several at once is on the way."]] as const;

function RepliesMockup() { return <ProductFrame title="Review inbox"><div className="divide-y divide-border">{["Maria G.", "Tom S.", "Ana R."].map((name, index) => <div key={name} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs tracking-[0.12em] text-accent-marigold">★★★★★ <span className="ml-1 tracking-normal text-primary">{name}</span></p><p className="mt-1 text-xs text-muted-foreground">A new review is ready for your voice.</p></div><span className="rounded-full bg-tint-navy px-2.5 py-1 text-[10px] font-bold text-navy">{index === 0 ? "Draft ready" : "Awaiting approval"}</span></div><div className="mt-3 rounded-xl border-[1.5px] border-navy/20 bg-tint-navy p-3"><div className="flex items-center gap-2 text-[10px] font-semibold text-navy"><Sparkles className="h-3 w-3" />Suggested reply</div><div className="hero-draft-bar mt-2 h-1.5 rounded-full bg-navy/15" /><div className="mt-1.5 h-1.5 w-3/4 rounded-full bg-navy/10" /></div></div>)}</div></ProductFrame>; }

export default function ReviewRepliesPage() {
  return <main><section className="py-16 md:py-24"><div className="mx-auto grid max-w-7xl items-center gap-14 px-4 md:grid-cols-2 md:px-6 lg:px-8"><div><span className="inline-flex items-center gap-2 rounded-full border border-border bg-tint-navy px-3 py-1.5 text-[0.7rem] font-bold uppercase tracking-[0.12em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-navy" />Review Replies</span><h1 className="mt-6 text-balance text-[clamp(2.8rem,6vw,4.8rem)] font-extrabold leading-[1.02] text-primary">Reply to every review like you had all day for it.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">Ornigami drafts a reply in your tone the moment a review lands. Read it, change anything, and approve — or let the replies you trust post on their own.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" variant="accent" asChild><Link href="/signup">Start free trial <ArrowRight className="h-4 w-4" /></Link></Button><Button size="lg" variant="secondary" asChild><Link href="/demo-review-replies">See a live demo</Link></Button></div><p className="mt-6 text-sm text-muted-foreground">14-day free trial · No card required · Cancel anytime</p></div><RepliesMockup /></div></section><section className="border-y border-border bg-surface py-20 md:py-24"><div className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8"><SectionHeading eyebrow="How it works" title="A thoughtful reply, without the inbox sprawl." align="center" tint="navy" /><div className="mt-12 grid gap-5 md:grid-cols-3"><FeatureCard icon="message-square" label="In your inbox" title="Every review, in one place." body="See new, drafted, and replied reviews together so nothing quietly slips through." bullets={["Google review sync", "Filter by status", "One focused view"]} /><FeatureCard icon="sparkles" accent="navy" label="In your voice" title="Drafts that already sound like you." body="Set your tone and business context, then refine each draft in seconds." bullets={["Business-aware copy", "Language matching", "Edit before posting"]} /><FeatureCard icon="shield-check" accent="green" label="On your terms" title="Nothing posts until you approve." body="You decide what goes live. Automation stays optional and visible." bullets={["Approve every draft", "Clear status history", "Safe defaults"]} /></div></div></section><section className="bg-ink-900 py-20 md:py-24"><div className="mx-auto max-w-3xl px-4 md:px-6"><SectionHeading light eyebrow="Review Replies" title="Answer every review without living in your inbox." intro="A focused workflow gives every customer a thoughtful response while you keep the final say." align="center" tint="navy" /><div className="mt-10 space-y-3">{faqs.map(([question, answer]) => <FAQItem dark key={question} question={question} answer={answer} />)}</div></div></section><CTASection title="Give every review a thoughtful next step." body="Start free today — your first reply can be ready in minutes." /></main>;
}
