import Link from "next/link";
import { ArrowRight, Check, MessageSquare, Send } from "lucide-react";

import { JsonLd } from "@/components/seo/json-ld";
import { Button } from "@/components/ui/button";
import { CTASection, Eyebrow, FAQItem, Marquee, ProductFrame, SectionHeading, StatRow, TintCard } from "@/components/marketing/primitives";
import { createPageMetadata } from "@/lib/seo";

const faqs = [
  ["Do I need a website?", "No. Ornigami works with your Google Business Profile, with or without a website."],
  ["Will the replies really sound like me?", "Yes. You set your tone and a little about your business, and you can edit any draft before it posts."],
  ["Is there a free trial?", "Yes — 14 days, no card required. You can cancel anytime from billing."],
  ["What does Review Booster do?", "After a visit, it sends a friendly follow-up that makes it easy for happy customers to leave a review."],
  ["Will anything post without me?", "Not unless you choose it. Approve-first is the default; automatic replies are optional and only for the cases you allow."],
  ["Can I manage more than one location?", "For now, one location per subscription. Managing several at once is on the way."],
] as const;

export const metadata = createPageMetadata({
  title: "Local reputation tools for reviews and follow-ups | Ornigami",
  description: "Ornigami helps local businesses answer Google reviews, follow up with customers, and keep their local visibility moving.",
  path: "/",
});

function ReviewProductMockup({ compact = false }: { compact?: boolean }) {
  return <ProductFrame title="Review inbox" className={compact ? "mt-6 shadow-none" : "animate-product-float"}>
    <div className="flex items-center justify-between bg-surface px-4 py-3 text-xs"><span className="text-muted-foreground">3 reviews today</span><span className="font-semibold text-primary">100% reply rate</span></div>
    <div className="divide-y divide-border">{[{ author: "Maria G.", text: "Fantastic service. We had a wonderful evening.", status: "Sent" }, { author: "Tom S.", text: "Great food, a little loud on weekends.", status: "Draft ready" }, { author: "Ana R.", text: "My favourite spot in the whole city.", status: "Draft ready" }].map((review) => <div key={review.author} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-1.5"><span className="text-xs tracking-[0.12em] text-accent-marigold" aria-label="5 out of 5 stars">★★★★★</span><span className="text-xs font-semibold text-primary">{review.author}</span></div><p className="mt-1 text-xs text-muted-foreground">{review.text}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-bold ${review.status === "Sent" ? "bg-tint-mint text-accent-green" : "bg-tint-navy text-navy"}`}>{review.status}</span></div>{review.status !== "Sent" ? <div className="mt-3 rounded-xl border-[1.5px] border-navy/20 bg-tint-navy p-3"><div className="flex items-center justify-between text-[10px] font-bold text-navy"><span>Suggested reply</span><span className="font-mono">READY</span></div><div className="hero-draft-bar mt-2 h-1.5 rounded-full bg-navy/15" /><div className="mt-2 h-1.5 w-3/4 rounded-full bg-navy/10" /></div> : null}</div>)}</div>
    <div className="flex items-center justify-between border-t border-border bg-surface px-4 py-3 text-[11px]"><span className="text-muted-foreground">This week</span><span className="font-mono font-semibold text-primary">0 awaiting approval</span></div>
  </ProductFrame>;
}

function BoosterProductMockup() {
  return <ProductFrame title="Review Booster"><div className="grid grid-cols-3 gap-2 border-b border-border bg-surface p-4 text-center text-xs"><div><div className="font-mono text-lg font-semibold text-primary">128</div><div className="text-muted-foreground">Visits</div></div><div><div className="font-mono text-lg font-semibold text-primary">94</div><div className="text-muted-foreground">Sent</div></div><div><div className="font-mono text-lg font-semibold text-primary">37</div><div className="text-muted-foreground">Replies</div></div></div><div className="space-y-3 p-4">{[["Jordan Lee", "Scheduled", "text-accent-marigold"], ["Priya Shah", "Sent", "text-accent-green"], ["Marco Ruiz", "Replied", "text-navy"]].map(([name, status, color]) => <div key={name} className="flex items-center justify-between rounded-xl border-[1.5px] border-border bg-card px-3 py-2.5 text-xs"><span className="font-semibold text-primary">{name}</span><span className={`font-bold ${color}`}>{status}</span></div>)}</div></ProductFrame>;
}

function AuditProductMockup() {
  return <ProductFrame title="Profile check" live={false} className="mt-6 shadow-none"><div className="flex items-center justify-between border-b border-border bg-surface px-4 py-3"><span className="text-xs font-semibold text-primary">Google Business Profile</span><span className="rounded-full bg-tint-butter px-2 py-1 text-[10px] font-bold text-primary">67/100</span></div><div className="divide-y divide-border">{[["Business details", "Complete", "text-accent-green"], ["Photos", "Needs attention", "text-accent-marigold"], ["Description", "Missing", "text-destructive"]].map(([label, status, color]) => <div key={label} className="flex items-center justify-between px-4 py-3 text-xs"><span className="text-muted-foreground">{label}</span><span className={`font-bold ${color}`}>{status}</span></div>)}</div></ProductFrame>;
}

export default function HomePage() {
  return <>
    <JsonLd data={{ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }} />
    <main>
      <section className="relative overflow-hidden py-16 md:py-24"><div className="pointer-events-none absolute right-[-10%] top-16 -z-10 h-80 w-80 rotate-45 rounded-[3rem] bg-surface/70 opacity-70" /><div className="mx-auto grid max-w-7xl items-center gap-14 px-4 md:px-6 lg:grid-cols-[1.02fr_.98fr] lg:px-8"><div><Eyebrow tint="navy">Reviews, handled</Eyebrow><h1 className="mt-6 max-w-3xl text-balance text-[clamp(2.9rem,6vw,5rem)] font-extrabold leading-[1.02] tracking-tight text-primary">Every review, answered in <span className="text-accent-marigold">your</span> voice.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">Ornigami brings your Google reviews into one place and drafts a reply in your tone. You read it, adjust anything, and approve. When a visit goes well, it gently follows up so happy customers remember to leave a review.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" variant="accent" asChild><Link href="/signup">Start free trial <ArrowRight className="h-4 w-4" /></Link></Button><Button size="lg" variant="secondary" asChild><Link href="/demo">See a live demo</Link></Button></div><p className="mt-6 text-sm text-muted-foreground">14-day free trial · No card required · Cancel anytime</p></div><div><ReviewProductMockup /></div></div></section>
      <section className="border-y border-border bg-surface py-20 md:py-24"><div className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8"><SectionHeading eyebrow="What Ornigami does" title="Three quiet jobs, one workspace." intro="The customer-facing work that keeps slipping is now handled in the background, always with your final say." align="center" tint="butter" /><div className="mt-12 grid gap-5 md:grid-cols-3"><TintCard icon="send" tint="mint" accent="green" label="Review Booster" title="More reviews, the honest way." body="A friendly message after a visit makes it easy for happy customers to leave a review." bullets={["Well-timed, friendly follow-ups", "Your review link, your words"]} href="/review-booster"><BoosterProductMockup /></TintCard><TintCard icon="message-square" tint="navy" accent="navy" label="Review Replies" title="Every review gets a reply." body="Your reviews land in one inbox with a draft already written in your voice. Approve before anything posts." bullets={["Your whole review inbox in one place", "Drafts that already sound like you"]} href="/review-replies"><ReviewProductMockup compact /></TintCard><TintCard icon="search" tint="butter" accent="marigold" label="Local visibility" title="Easy to find nearby." body="Small, clear fixes keep your Google profile complete and working for you." bullets={["Profile completeness checks", "Simple, ordered next steps"]} href="/local-seo"><AuditProductMockup /></TintCard></div></div></section>
      <section className="bg-ink-900 py-20 md:py-24"><div className="mx-auto max-w-7xl space-y-20 px-4 md:px-6 lg:px-8"><div className="grid items-center gap-12 lg:grid-cols-2"><div className="order-2 lg:order-1"><BoosterProductMockup /></div><div className="order-1 lg:order-2"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-accent-green"><Send className="h-5 w-5" /></div><Eyebrow light tint="mint">Review Booster</Eyebrow><h2 className="mt-4 text-balance text-3xl font-extrabold text-background sm:text-4xl">Turn good visits into reviews, gently.</h2><p className="mt-4 max-w-xl text-lg leading-relaxed text-background/70">Log a visit or upload a list, and Ornigami sends a warm follow-up at the right moment, so the customers who loved you find it easy to say so.</p><ul className="mt-6 space-y-3 text-sm text-background/70">{["Well-timed, friendly follow-ups", "Your review link, your words", "See sends and new reviews in one place"].map((item) => <li key={item} className="flex items-start gap-2.5"><Check className="mt-0.5 h-4 w-4 shrink-0 text-accent-green" />{item}</li>)}</ul><Button className="mt-8" variant="primary-on-ink" asChild><Link href="/review-booster">See Review Booster <ArrowRight className="h-4 w-4" /></Link></Button></div></div><div className="grid items-center gap-12 lg:grid-cols-2"><div><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-navy"><MessageSquare className="h-5 w-5" /></div><Eyebrow light>Review Replies</Eyebrow><h2 className="mt-4 text-balance text-3xl font-extrabold text-background sm:text-4xl">Answer every review without living in your inbox.</h2><p className="mt-4 max-w-xl text-lg leading-relaxed text-background/70">The moment a review arrives, Ornigami has a reply ready in your tone. You stay in control. Read it, adjust it, approve it. Nothing posts until you say so.</p><ul className="mt-6 space-y-3 text-sm text-background/70">{["Your whole review inbox in one place", "Drafts that already sound like you", "Approve-first, always"].map((item) => <li key={item} className="flex items-start gap-2.5"><Check className="mt-0.5 h-4 w-4 shrink-0 text-accent-green" />{item}</li>)}</ul><Button className="mt-8" variant="primary-on-ink" asChild><Link href="/review-replies">See Review Replies <ArrowRight className="h-4 w-4" /></Link></Button></div><div><ReviewProductMockup /></div></div></div></section>
      <section className="bg-surface py-20 md:py-24"><div className="mx-auto max-w-7xl space-y-10 px-4 md:px-6 lg:px-8"><SectionHeading eyebrow="Made for local teams" title="Small teams, growing reputations." intro="Illustrative product signals and example customer language, so you can see the rhythm at a glance." align="center" tint="peach" /><StatRow stats={[{ value: "<1 min", label: "Average reply time", detail: "Example workflow" }, { value: "100", label: "Reviews answered", detail: "Example workspace" }, { value: "128", label: "Follow-ups sent", detail: "Example workspace" }]} /><Marquee items={[{ name: "Maria G.", quote: "Warm, thoughtful, and ready to send." }, { name: "Tom S.", quote: "The draft sounded like us." }, { name: "Ana R.", quote: "A calmer way to stay on top of reviews." }, { name: "Priya S.", quote: "Nothing slipped through this week." }]} /></div></section>
      <section className="py-20 md:py-24"><div className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8"><SectionHeading eyebrow="A day with Ornigami" title="A normal day, handled." intro="A few illustrative moments — not customer stories — showing how Ornigami fits around the work already happening." align="center" tint="mint" /><div className="mt-12 grid gap-5 md:grid-cols-3"><TintCard icon="message-square" tint="navy" accent="navy" label="Example workflow" title="Morning" body="A new 4-star review arrives, and a thoughtful reply is waiting before your first appointment." /><TintCard icon="clock" tint="peach" accent="coral" label="Example workflow" title="Afternoon" body="A visit wraps up, and a warm follow-up goes out while the experience is still fresh." /><TintCard icon="bar-chart" tint="butter" accent="marigold" label="Example workflow" title="Evening" body="A quick glance shows what is answered, what is pending, and what is worth a look." /></div></div></section>
      <section className="bg-surface py-20 md:py-24"><div className="mx-auto max-w-3xl px-4 md:px-6"><SectionHeading eyebrow="Questions" title="Answers before you start." align="center" tint="navy" /><div className="mt-10 space-y-3">{faqs.map(([question, answer]) => <FAQItem key={question} question={question} answer={answer} />)}</div></div></section>
      <CTASection title="A calmer way to keep your reputation growing." body="Start free today by connecting your Google profile takes about five minutes." />
    </main>
  </>;
}
