import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";

import { Button } from "@/components/ui/button";
import { CTASection, FeatureCard, PageHero, ProductFrame, SectionHeading } from "@/components/marketing/primitives";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Local SEO tools for Google Business Profiles | Ornigami", description: "Find the small Google Business Profile gaps that cost local businesses visibility, then work through clear next steps.", path: "/local-seo" });

export default function LocalSeoPage() {
  return <main><PageHero eyebrow="Local visibility" title="Easy to find when your neighbors search." intro="Ornigami looks over your Google Business Profile for the small gaps that quietly cost you customers, and shows you exactly what to fix — no guesswork." /><section className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 md:grid-cols-2 md:px-6 lg:px-8"><div><SectionHeading eyebrow="What we check" title="Know what to improve, then make the next update." intro="Small, ordered actions keep your profile complete and working for you." tint="butter" /><ul className="mt-7 space-y-3">{["Profile completeness", "The details that help you rank", "Simple, ordered next steps"].map((item) => <li key={item} className="flex items-center gap-2.5 text-sm text-primary"><Check className="h-4 w-4 text-accent-green" />{item}</li>)}</ul><div className="mt-8"><Button variant="accent" asChild><Link href="/signup">Start free trial <ArrowRight className="h-4 w-4" /></Link></Button></div></div><ProductFrame title="Profile check" live={false}><div className="flex items-center justify-between border-b border-border bg-surface px-4 py-3"><span className="text-xs font-semibold text-primary">Google Business Profile</span><span className="rounded-full bg-tint-butter px-2.5 py-1 text-[10px] font-bold text-primary">Example · 67/100</span></div><div className="divide-y divide-border">{[["Business details", "Complete", "text-accent-green"], ["Photos", "Needs attention", "text-accent-marigold"], ["Description", "Missing", "text-destructive"], ["Recent posts", "Needs attention", "text-accent-marigold"]].map(([label, status, color]) => <div key={label} className="flex items-center justify-between px-4 py-4 text-sm"><span className="text-muted-foreground">{label}</span><span className={`font-semibold ${color}`}>{status}</span></div>)}</div><div className="m-4 rounded-xl bg-tint-mint px-4 py-3 text-xs font-semibold text-primary">4 useful next steps ready</div></ProductFrame></section><section className="border-y border-border bg-surface py-20"><div className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8"><SectionHeading eyebrow="A clear visibility toolkit" title="Stay active without making content your second job." align="center" tint="navy" /><div className="mt-12 grid gap-5 md:grid-cols-3"><FeatureCard icon="file-text" title="Write locally" body="Create starting points for Google updates, posts, and FAQs that reflect your place and services." /><FeatureCard icon="map-pin" accent="green" title="Keep context" body="Use your business name, location, and niche so the work starts closer to publishable." /><FeatureCard icon="bar-chart" accent="marigold" title="See the gaps" body="Review the profile details that need attention and work through them in a sensible order." /></div></div></section><CTASection title="Make local visibility easier to keep up with." body="Start free today — your Google profile is the place to begin." /></main>;
}
