"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, Check, FileText, MapPin } from "lucide-react";

import { Button } from "@/components/ui/button";
import { CTASection, FeatureCard, PageHero, SectionHeading } from "@/components/marketing/primitives";

export default function LocalSeoPage() {
  return <main><PageHero eyebrow="Local visibility" title="Content and profile work that helps you get found." intro="Keep your Google Business Profile complete and create locally relevant content without starting from a blank page." /><section className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-20 md:grid-cols-2 md:px-6 lg:px-8"><div><SectionHeading eyebrow="A clearer visibility workflow" title="Know what to improve, then make the next update." intro="Ornigami turns local SEO into a short list of useful actions — from profile gaps to content ideas for your city and niche." /><ul className="mt-7 space-y-3">{["Profile completeness checks", "Locally relevant post and FAQ ideas", "A score with practical next steps"].map((item) => <li key={item} className="flex items-center gap-2.5 text-sm text-primary"><Check className="h-4 w-4 text-accent-green" />{item}</li>)}</ul><div className="mt-8"><Button asChild><Link href="/signup">Start free trial <ArrowRight className="h-4 w-4" /></Link></Button></div></div><div className="rounded-2xl border border-border bg-card p-5 shadow-md"><div className="flex items-center justify-between border-b border-border pb-4"><span className="text-sm font-semibold text-primary">Profile audit</span><span className="rounded-full bg-surface px-2.5 py-1 text-xs font-semibold text-accent-yellow">Score: 67/100</span></div><div className="divide-y divide-border">{[["Business details", "Complete", "text-accent-green"], ["Photos", "Needs attention", "text-accent-yellow"], ["Description", "Missing", "text-destructive"], ["Recent posts", "Needs attention", "text-accent-yellow"]].map(([label, status, color]) => <div key={label} className="flex items-center justify-between py-4 text-sm"><span className="text-muted-foreground">{label}</span><span className={`font-semibold ${color}`}>{status}</span></div>)}</div><div className="mt-2 rounded-xl bg-surface px-4 py-3 text-xs font-medium text-primary">4 useful next steps ready</div></div></section><section className="border-y border-border bg-surface py-20"><div className="mx-auto max-w-7xl px-4 md:px-6 lg:px-8"><SectionHeading eyebrow="One visibility toolkit" title="Stay active without making content your second job." align="center" /><div className="mt-12 grid gap-5 md:grid-cols-3"><FeatureCard icon={FileText} title="Write locally" body="Create starting points for blog posts, Google updates, and FAQs that reflect your place and services." /><FeatureCard icon={MapPin} accent="green" title="Keep context" body="Use your business name, location, and niche so the work starts closer to publishable." /><FeatureCard icon={BarChart3} accent="yellow" title="See the gaps" body="Review the profile details that need attention and work through them in a sensible order." /></div></div></section><CTASection title="Make visibility work easier to keep up with." body="Start a 14-day free trial with no card required." /></main>;
}
